In [ ]:
import pandas as pd
# Creazione del dataframe(studenti) = dataset(tabella) 
studenti = {
    "nome": ["Mario", "Rudy", "Marco", "Roberta", "Anna", "Silvia"],
    "cognome": ["Ricci", "Botosso", "Secci", "Rossi", "Bianchi", "Verdi"],
    "eta": [30, 54, 54, 44, 23, 55],
    "citta": ["Milano", "Biella", "San Donà di Piave", "Napoli", "Roma", "Bari"],
    "voto": [8, 9, 7, 9, 4, 6],
    "stipendio": [2000, 3000, 4000, 2500, 1000, 3500]
}

# chiama pandas e crea un dataframe a partire dal dizionario studenti
df = pd.DataFrame(studenti)
df # stampa il dataframe(tipo tabella) con i dati degli studenti
print(df) # stampa il dataframe(tipo tabella in formato csv)

      nome  cognome  eta              citta  voto  stipendio
0    Mario    Ricci   30             Milano     8       2000
1     Rudy  Botosso   54             Biella     9       3000
2    Marco    Secci   54  San Donà di Piave     7       4000
3  Roberta    Rossi   44             Napoli     9       2500
4     Anna  Bianchi   23               Roma     4       1000
5   Silvia    Verdi   55               Bari     6       3500

Filtri in pandas

In [ ]:
df[df["stipendio"] >= 2500] #select * from dipendenti where stipendio >= 2500

      nome  cognome  eta              citta  voto  stipendio
1     Rudy  Botosso   54             Biella     9       3000
2    Marco    Secci   54  San Donà di Piave     7       4000
3  Roberta    Rossi   44             Napoli     9       2500
5   Silvia    Verdi   55               Bari     6       3500

In [4]:
#select stipendio
df[df["nome"] == "Giovanni"]["stipendio"]

Series([], Name: stipendio, dtype: int64)

In [8]:

df[df['stipendio'] == 2500][['nome', 'cognome']]

      nome cognome
3  Roberta   Rossi

In [ ]:
df[df['nome'].str.endswith('a')]
#nomi che finiscono con a

      nome  cognome  eta   citta  voto  stipendio
3  Roberta    Rossi   44  Napoli     9       2500
4     Anna  Bianchi   23    Roma     4       1000
5   Silvia    Verdi   55    Bari     6       3500

In [17]:
#colonna citta contiene questa lettera:
df[df['citta'].str.contains('n')]

    nome cognome  eta              citta  voto  stipendio
0  Mario   Ricci   30             Milano     8       2000
2  Marco   Secci   54  San Donà di Piave     7       4000