# Le condizioni
- AND
- NOT
- OR

In [23]:
import pandas as pd

# Creazione del dataframe(dipendenti) = dataset(Tabella, Modello, Entity) 
dipendenti = {
    "nome": ["Mario", "Rudy", "Marco", "Luca", "Giovanni", "Francesco", "Giulia", "Elena", "Federica", "Alessandro"],
    "cognome": ["Ricci", "Botosso", "Secci", "Bianchi", "Neri", "Rossi", "Verdi", "Gialli", "Blu", "Rosa"],
    "email": ["mario.ricci@example.info", "rudy.botosso@example.it", "marco.secci@example.com", "luca.bianchi@example.ca", "giovanni.neri@example.com", "francesco.rossi@example.ue", "giulia.verdi@example.com", "elena.gialli@example.it", "federica.blu@example.com", "alessandro.rosa@example.info"],
    "eta": [30, 54, 54, 28, 35, 42, 28, 32, 29, 31],
    "citta": ["Milano", "Biella", "San Donà di Piave", "Roma", "Napoli", "Torino", "Firenze", "Bologna", "Genova", "Padova"],
    "stipendio": [2000, 3000, 1500, 2500, 3500, 4000, 2500, 3000, 3500, 4000],
    "ruolo": ["Sviluppatore", "Project Manager", "Analista", "Sviluppatore", "Team Leader", "Project Manager", "Sviluppatore", "Analista", "Team Leader", "Project Manager"],
    "data_assunzione": ["2015-01-15", "2010-06-30", "2018-09-01", "2016-03-20", "2012-11-05", "2008-04-10", "2017-07-25", "2014-02-18", "2013-12-12", "2009-08-01"]
}

# chiama pandas e crea un dataframe a partire dal dizionario dipendenti
df = pd.DataFrame(dipendenti)
df # stampa il dataframe(tipo tabella) con i dati dei dipendenti

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
0,Mario,Ricci,mario.ricci@example.info,30,Milano,2000,Sviluppatore,2015-01-15
1,Rudy,Botosso,rudy.botosso@example.it,54,Biella,3000,Project Manager,2010-06-30
2,Marco,Secci,marco.secci@example.com,54,San Donà di Piave,1500,Analista,2018-09-01
3,Luca,Bianchi,luca.bianchi@example.ca,28,Roma,2500,Sviluppatore,2016-03-20
4,Giovanni,Neri,giovanni.neri@example.com,35,Napoli,3500,Team Leader,2012-11-05
5,Francesco,Rossi,francesco.rossi@example.ue,42,Torino,4000,Project Manager,2008-04-10
6,Giulia,Verdi,giulia.verdi@example.com,28,Firenze,2500,Sviluppatore,2017-07-25
7,Elena,Gialli,elena.gialli@example.it,32,Bologna,3000,Analista,2014-02-18
8,Federica,Blu,federica.blu@example.com,29,Genova,3500,Team Leader,2013-12-12
9,Alessandro,Rosa,alessandro.rosa@example.info,31,Padova,4000,Project Manager,2009-08-01

In [20]:
# AND
df[(df['stipendio'] >= 2500) & (df['stipendio'] <= 3000)]
df[(df['stipendio'] >= 2500) & (df['stipendio'] <= 3000)][['nome', 'cognome', 'ruolo']]

     nome  cognome            ruolo
1    Rudy  Botosso  Project Manager
3    Luca  Bianchi     Sviluppatore
6  Giulia    Verdi     Sviluppatore
7   Elena   Gialli         Analista

In [25]:
df[(df['stipendio'] >= 2000) & (df['stipendio'] <= 3000) & (df['ruolo'] == 'Sviluppatore')]

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
0,Mario,Ricci,mario.ricci@example.info,30,Milano,2000,Sviluppatore,2015-01-15
3,Luca,Bianchi,luca.bianchi@example.ca,28,Roma,2500,Sviluppatore,2016-03-20
6,Giulia,Verdi,giulia.verdi@example.com,28,Firenze,2500,Sviluppatore,2017-07-25

In [29]:
# OR
df[(df['ruolo'] == 'Sviluppatore') | (df['ruolo'] == 'Project Manager')]

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
0,Mario,Ricci,mario.ricci@example.info,30,Milano,2000,Sviluppatore,2015-01-15
1,Rudy,Botosso,rudy.botosso@example.it,54,Biella,3000,Project Manager,2010-06-30
3,Luca,Bianchi,luca.bianchi@example.ca,28,Roma,2500,Sviluppatore,2016-03-20
5,Francesco,Rossi,francesco.rossi@example.ue,42,Torino,4000,Project Manager,2008-04-10
6,Giulia,Verdi,giulia.verdi@example.com,28,Firenze,2500,Sviluppatore,2017-07-25
9,Alessandro,Rosa,alessandro.rosa@example.info,31,Padova,4000,Project Manager,2009-08-01

In [30]:
df[(df['data_assunzione'] == '2010-06-30') | (df['nome'] == 'Rudy')]

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
1,Rudy,Botosso,rudy.botosso@example.it,54,Biella,3000,Project Manager,2010-06-30

In [31]:
# NOT
df[~((df['ruolo'] == 'Sviluppatore') | (df['ruolo'] == 'Project Manager'))]

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
2,Marco,Secci,marco.secci@example.com,54,San Donà di Piave,1500,Analista,2018-09-01
4,Giovanni,Neri,giovanni.neri@example.com,35,Napoli,3500,Team Leader,2012-11-05
7,Elena,Gialli,elena.gialli@example.it,32,Bologna,3000,Analista,2014-02-18
8,Federica,Blu,federica.blu@example.com,29,Genova,3500,Team Leader,2013-12-12

In [32]:
import pandas as pd

# Creazione del dataframe(dipendenti) = dataset(Tabella, Modello, Entity) 
dipendenti = {
    "nome": ["Mario", "Rudy", "Marco", "Luca", "Giovanni", "Francesco", "Giulia", "Elena", "Federica", "Alessandro"],
    "cognome": ["Ricci", "Botosso", "Secci", "Bianchi", "Neri", "Rossi", "Verdi", "Gialli", "Blu", "Rosa"],
    "email": ["mario.ricci@example.info", None , "marco.secci@example.com", None, "giovanni.neri@example.com", "francesco.rossi@example.ue", "giulia.verdi@example.com", "elena.gialli@example.it", "federica.blu@example.com", "alessandro.rosa@example.info"],
    "eta": [30, 54, 54, 28, 35, 42, 28, 32, 29, 31],
    "citta": ["Milano", "Biella", "San Donà di Piave", "Roma", "Napoli", "Torino", "Firenze", "Bologna", "Genova", "Padova"],
    "stipendio": [2000, 3000, 1500, 2500, 3500, 4000, 2500, 3000, 3500, 4000],
    "ruolo": ["Sviluppatore", "Project Manager", "Analista", "Sviluppatore", "Team Leader", "Project Manager", "Sviluppatore", "Analista", "Team Leader", "Project Manager"],
    "data_assunzione": ["2015-01-15", "2010-06-30", "2018-09-01", "2016-03-20", "2012-11-05", "2008-04-10", "2017-07-25", "2014-02-18", "2013-12-12", "2009-08-01"]
}

# chiama pandas e crea un dataframe a partire dal dizionario dipendenti
df = pd.DataFrame(dipendenti)
df # stampa il dataframe(tipo tabella) con i dati dei dipendenti

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
0,Mario,Ricci,mario.ricci@example.info,30,Milano,2000,Sviluppatore,2015-01-15
1,Rudy,Botosso,NaN,54,Biella,3000,Project Manager,2010-06-30
2,Marco,Secci,marco.secci@example.com,54,San Donà di Piave,1500,Analista,2018-09-01
3,Luca,Bianchi,NaN,28,Roma,2500,Sviluppatore,2016-03-20
4,Giovanni,Neri,giovanni.neri@example.com,35,Napoli,3500,Team Leader,2012-11-05
5,Francesco,Rossi,francesco.rossi@example.ue,42,Torino,4000,Project Manager,2008-04-10
6,Giulia,Verdi,giulia.verdi@example.com,28,Firenze,2500,Sviluppatore,2017-07-25
7,Elena,Gialli,elena.gialli@example.it,32,Bologna,3000,Analista,2014-02-18
8,Federica,Blu,federica.blu@example.com,29,Genova,3500,Team Leader,2013-12-12
9,Alessandro,Rosa,alessandro.rosa@example.info,31,Padova,4000,Project Manager,2009-08-01

In [33]:
# IS NULL
df[df['email'].isnull()]

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
1,Rudy,Botosso,NaN,54,Biella,3000,Project Manager,2010-06-30
3,Luca,Bianchi,NaN,28,Roma,2500,Sviluppatore,2016-03-20

In [35]:
# IS NOT NULL
df[df['email'].notnull()]

,nome,cognome,email,eta,citta,stipendio,ruolo,data_assunzione
0,Mario,Ricci,mario.ricci@example.info,30,Milano,2000,Sviluppatore,2015-01-15
2,Marco,Secci,marco.secci@example.com,54,San Donà di Piave,1500,Analista,2018-09-01
4,Giovanni,Neri,giovanni.neri@example.com,35,Napoli,3500,Team Leader,2012-11-05
5,Francesco,Rossi,francesco.rossi@example.ue,42,Torino,4000,Project Manager,2008-04-10
6,Giulia,Verdi,giulia.verdi@example.com,28,Firenze,2500,Sviluppatore,2017-07-25
7,Elena,Gialli,elena.gialli@example.it,32,Bologna,3000,Analista,2014-02-18
8,Federica,Blu,federica.blu@example.com,29,Genova,3500,Team Leader,2013-12-12
9,Alessandro,Rosa,alessandro.rosa@example.info,31,Padova,4000,Project Manager,2009-08-01